
# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'
        
scrape_configs:

  - job_name: 'traefik'
    basic_auth:
      username: admin
      password: changeme
    static_configs:
    - targets: ['traefik:8080']

  - job_name: 'node-metrics'
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'cadvisor-service'
    static_configs:
    - targets: ['cadvisor:8080']
      labels:
        alias: "cadvisor"
